import type { UIRPackageData, UIRRecord } from "./runtime.ts";

const records: UIRRecord[] = [
  { id: "example:surface:home", recordType: "Entity", kind: "Surface" },
  { id: "example:node:document", recordType: "Entity", kind: "Node" },
  { id: "example:node:hero", recordType: "Entity", kind: "Node" },
  { id: "example:node:title", recordType: "Entity", kind: "Node" },
  { id: "example:node:copy", recordType: "Entity", kind: "Node" },
  { id: "example:node:actions", recordType: "Entity", kind: "Node" },
  { id: "example:node:primary", recordType: "Entity", kind: "Node" },
  { id: "example:node:secondary", recordType: "Entity", kind: "Node" },
  { id: "example:node:proof", recordType: "Entity", kind: "Node" },
  { id: "example:node:proof-title", recordType: "Entity", kind: "Node" },
  { id: "example:node:proof-list", recordType: "Entity", kind: "Node" },
  { id: "example:node:item-1", recordType: "Entity", kind: "Node" },
  { id: "example:node:item-2", recordType: "Entity", kind: "Node" },
  { id: "example:node:item-3", recordType: "Entity", kind: "Node" },
  { id: "example:gap:proof", recordType: "Entity", kind: "Gap", target: "example:node:proof", rationale: "The proof section intentionally leaves the evidence visualization unspecified." },
  { id: "example:source:brief", recordType: "Entity", kind: "Source", locator: "https://uir.dev" },
  { id: "example:prov:declared", recordType: "Provenance", mode: "declared", sources: ["example:source:brief"] },
  { id: "example:prov:inferred", recordType: "Provenance", mode: "inferred", sources: ["example:source:brief"] },
  { id: "example:piece:document", recordType: "Entity", kind: "Piece" },
  { id: "example:piece:section", recordType: "Entity", kind: "Piece" },
  { id: "example:piece:heading", recordType: "Entity", kind: "Piece" },
  { id: "example:piece:text", recordType: "Entity", kind: "Piece" },
  { id: "example:piece:button", recordType: "Entity", kind: "Piece" },
  { id: "example:piece:list", recordType: "Entity", kind: "Piece" },
  { id: "example:piece:item", recordType: "Entity", kind: "Piece" },
  { id: "example:resolution:document", recordType: "Entity", kind: "Resolution", outcome: "example:piece:document" },
  { id: "example:resolution:region", recordType: "Entity", kind: "Resolution", outcome: "example:piece:section" },
  { id: "example:resolution:heading", recordType: "Entity", kind: "Resolution", outcome: "example:piece:heading" },
  { id: "example:resolution:paragraph", recordType: "Entity", kind: "Resolution", outcome: "example:piece:text" },
  { id: "example:resolution:button", recordType: "Entity", kind: "Resolution", outcome: "example:piece:button" },
  { id: "example:resolution:list", recordType: "Entity", kind: "Resolution", outcome: "example:piece:list" },
  { id: "example:resolution:listitem", recordType: "Entity", kind: "Resolution", outcome: "example:piece:item" },
  { id: "example:package", recordType: "Fact", kind: "package.metadata", subject: "example:package", value: { name: "UIR Playground example", summary: "A small semantic surface bundled with the standalone playground." } },
  { id: "example:source-name", recordType: "Fact", kind: "source.description", subject: "example:source:brief", value: { name: "UIR reference" } },
  ...[
    ["example:node:document", "document", ""],
    ["example:node:hero", "region", ""],
    ["example:node:title", "heading", "Inspect what the interface means."],
    ["example:node:copy", "paragraph", "UIR separates semantic intent from framework rendering, so agents and tools can inspect the same interface model."],
    ["example:node:actions", "group", ""],
    ["example:node:primary", "button", "Open a custom UIR"],
    ["example:node:secondary", "button", "Inspect the example"],
    ["example:node:proof", "region", ""],
    ["example:node:proof-title", "heading", "What this package proves"],
    ["example:node:proof-list", "list", ""],
    ["example:node:item-1", "listitem", "Semantic structure is explicit."],
    ["example:node:item-2", "listitem", "Resolution to a design system is inspectable."],
    ["example:node:item-3", "listitem", "Provenance and gaps stay visible."],
  ].flatMap(([subject, role, content], index): UIRRecord[] => [
    { id: `example:fact:role:${index}`, recordType: "Fact", kind: "node.role", subject, plane: "interface", provenance: index === 11 ? "example:prov:inferred" : "example:prov:declared", value: { role } },
    ...(content ? [{ id: `example:fact:content:${index}`, recordType: "Fact", kind: "node.content", subject, plane: "interface", provenance: "example:prov:declared", value: { type: "text", value: content } } as UIRRecord] : []),
  ]),
  ...[
    ["example:resolution:document", "document"],
    ["example:resolution:region", "region"],
    ["example:resolution:heading", "heading"],
    ["example:resolution:paragraph", "paragraph"],
    ["example:resolution:button", "button"],
    ["example:resolution:list", "list"],
    ["example:resolution:listitem", "listitem"],
  ].map(([subject, role], index): UIRRecord => ({ id: `example:fact:selector:${index}`, recordType: "Fact", kind: "resolution.selector", subject, plane: "resolution", value: { dimension: "role", role } })),
  ...[
    ["example:piece:document", "Document"],
    ["example:piece:section", "Section"],
    ["example:piece:heading", "Heading"],
    ["example:piece:text", "Text"],
    ["example:piece:button", "Button"],
    ["example:piece:list", "List"],
    ["example:piece:item", "List item"],
  ].map(([subject, name], index): UIRRecord => ({ id: `example:fact:piece:${index}`, recordType: "Fact", kind: "piece.identity", subject, plane: "design-system", value: { name } })),
  ...[
    ["example:surface:home", "example:node:document"],
    ["example:node:document", "example:node:hero"],
    ["example:node:hero", "example:node:title"],
    ["example:node:hero", "example:node:copy"],
    ["example:node:hero", "example:node:actions"],
    ["example:node:actions", "example:node:primary"],
    ["example:node:actions", "example:node:secondary"],
    ["example:node:document", "example:node:proof"],
    ["example:node:proof", "example:node:proof-title"],
    ["example:node:proof", "example:node:proof-list"],
    ["example:node:proof-list", "example:node:item-1"],
    ["example:node:proof-list", "example:node:item-2"],
    ["example:node:proof-list", "example:node:item-3"],
  ].map(([source, target], index): UIRRecord => ({ id: `example:rel:${index}`, recordType: "Relation", kind: "contains", source, target, order: index })),
];

export const examplePackage: UIRPackageData = {
  manifest: {
    formatVersion: "1.0",
    packageId: "example:package",
    packageVersion: "0.1.0",
    readingProfile: "authoring",
    vocabularyVersion: "0.1",
    model: [{ collection: "example", path: "model/example.json" }],
  },
  shards: { example: { records } },
  sourceName: "Built-in example",
  diagnostics: [
    { severity: "success", code: "example.loaded", message: "Built-in example package loaded" },
    { severity: "success", code: "manifest.found", message: "Manifest example:package · 0.1.0", path: "package.json" },
  ],
};
